model_opts:
  model: Transformer_depth
  # model: MASK_PCPA_4_2D
  obs_input_type: [box, depth, vehicle_speed, ped_speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True

net_opts:
  num_hidden_units: 256
  regularizer_val: 0.0001
  dropout: 0.1
exp_opts:
  datasets: [jaad_beh, jaad_all]
  batch_size: [1, 1]
  epochs: [80, 80]
  lr: [5.0e-06, 5.0e-06]

# exp_opts:
#   datasets: [jaad_all]
#   batch_size: [1]
#   epochs: [60]
#   lr: [5.0e-05]